# Generated by Django 2.2.8 on 2021-05-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('resolve', 'Решен'), ('cancel', 'Отменен')], default='open', max_length=10, verbose_name='Статус'),
        ),
    ]
