# Generated by Django 2.2.8 on 2021-05-05 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('admin', 'Администратор'), ('staff', 'Персонал'), ('client', 'Клиент')], default='client', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Профиль', to=settings.AUTH_USER_MODEL),
        ),
    ]
